datasets:
  hdvila:
    data_type: video
    build_info:
      anno_train: path/hdvila/hdvila_data/annotations_train.json
      anno_test: path/hdvila/hdvila_data/annotations_test.json
      videos_dir: path/hdvila/hdvila_data/videos/
